version: '3.4'

services:
  gateway.enrollment.management.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8000:80"

  enrollment.management.courses.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8001:80"

  enrollment.management.registration.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8002:80"
      
  enrollment.management.students.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8003:80"
