version: '3.4'

services:
  gateway.enrollment.management.webapi:
    image: ${DOCKER_REGISTRY-}gatewayenrollmentmanagementwebapi
    build:
      context: .
      dockerfile: Gateway.Enrollment.Management.WebAPI/Dockerfile

  enrollment.management.courses.api:
    image: ${DOCKER_REGISTRY-}enrollmentmanagementcoursesapi
    build:
      context: .
      dockerfile: Enrollment.Management.Courses.Api/Dockerfile






