version: '3.4'

services:

  gateway.enrollment.management.webapi:   
    container_name: gateway.api
    image: ${DOCKER_REGISTRY-}gatewaywebapi
    restart: on-failure
    build:
      context: .
      dockerfile: Gateway.Enrollment.Management.WebAPI/Dockerfile

  enrollment.management.courses.api:
    container_name: courses.api
    image: ${DOCKER_REGISTRY-}coursesapi
    restart: on-failure
    build:
      context: .
      dockerfile: Enrollment.Management.Courses.Api/Dockerfile

  enrollment.management.registration.api:
    container_name: registration.api
    image: ${DOCKER_REGISTRY-}registrationapi
    restart: on-failure
    build:
      context: .
      dockerfile: Enrollment.Management.Registration.Api/Dockerfile

  enrollment.management.students.api:
    container_name: students.api
    image: ${DOCKER_REGISTRY-}studentsapi
    restart: on-failure
    build:
      context: .
      dockerfile: Enrollment.Management.Students.Api/Dockerfile






