version: '3.4'

services:
  gateway.enrollment.management.webapi:
    image: ${DOCKER_REGISTRY-}gatewayenrollmentmanagementwebapi
    build:
      context: .
      dockerfile: Gateway.Enrollment.Management.WebAPI/Dockerfile

  enrollment.management.courses.api:
    image: ${DOCKER_REGISTRY-}enrollmentmanagementcoursesapi
    build:
      context: .
      dockerfile: MicroserviceCourses/Enrollment.Management.Courses.Api/Dockerfile

  enrollment.management.registration.api:
    image: ${DOCKER_REGISTRY-}enrollmentmanagementregistrationapi
    build:
      context: .
      dockerfile: MicroserviceRegistration/Enrollment.Management.Registration.Api/Dockerfile

  enrollment.management.students.api:
    image: ${DOCKER_REGISTRY-}enrollmentmanagementstudentsapi
    build:
      context: .
      dockerfile: MicroserviceStudents/Enrollment.Management.Students.Api/Dockerfile






